### ISSUE TITLE
Pseudo-terminal will not be allocated because stdin is not a terminal.

### ISSUE THREAD

**Issue by fraksken** [coderaiser/cloudcmd#105] opened 2017-02-13 06:27 UTC
Hello,

I'm running the docker container version of cloud Commander: v6.4.0

* **Version** (`cloudcmd -v`): v6.4.0
* **Node Version** `node -v`: v7.5.0
* **OS** (`uname -a` on Linux): docker: Linux 22583f13435c 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 GNU/Linux
* **Browser name/version**: FF 45.6.0

When opening the terminal window in Cloud Commander and issueing the "ssh host" command, I get the following error:
Pseudo-terminal will not be allocated because stdin is not a terminal.
It would be great if I could use this also for my ssh needs.

Thanks

**Comment by coderaiser** [comment] 2017-02-13 08:33
Duplicate of #103.

**Closed by coderaiser** 2017-02-13 08:33 UTC
Labels: duplicate

**Comment by coderaiser** [comment] 2017-03-04 12:22
Added support of a terminal in [v6.7.0](https://github.com/coderaiser/cloudcmd/releases/tag/v6.7.0).
