### ISSUE TITLE
Editor does not open file the second time

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#177] opened 2018-06-08 15:04 UTC
* **Version** : v10.1.1 
* **Node Version** : v10.4.0
* **OS**: Ubuntu 16/Ubuntu 18 
* **Browser name/version**: Chrome(multiple versions)/Firefox(60.0.1)
* **Used Command Line Parameters**:  none
* **Changed Config**:  no config

After editing a file, saving it and closing the editor it won't open the same file again and when trying to view it I get the message "undefined".

**Comment by coderaiser** [comment] 2018-06-09 08:43
Thank you :), fixed with 55488ae2. Landed in [v10.1.2](https://github.com/coderaiser/cloudcmd/releases/tag/v10.1.2)

**Closed by coderaiser** 2018-06-09 08:43 UTC
Labels: browser, bug, chrome, firefox, linux, node, node v10, os

**Comment by ulno** [comment] 2018-09-24 20:52
I cannot confirm this fix. In my case an edit of a file does get saved, however either using F3 to view or F4 to edit does not give me the correct content - it only shows me the content from before I edited (can confirm this both in chromium and in firefox).
ctrl-r updates the files-size, and download retrieves the correct contents (the one after the edit), but there is no way to continue editing or to fix mistakes in the file anymore. It will always just show the initial contents.

Not sure if that matters, but I use deepword as editor.
Update, the mistake does not occur in edward and dword - so definetely a problem just with deepword.

**Comment by coderaiser** [comment] 2018-09-25 08:49
@ulno what version of `Cloud Commander` are you using? What version of a `deepword` installed in your `node_modules`?

**Comment by caracal7** [comment] 2019-08-21 07:40
I have the same problem 
cloudcmd@13.1.0 in middleware mode
OSX 10.13.6
node.js 12.4.1

After editing any file 
```Unhandled Promise Rejection: TypeError: t is not a function. (In 't(null,e)', 't' is "/Users/caracal/11111111/rubr_ns.sql")```
And if I try to view it(F3) I get the message `undefined`
But if I download file - file is correct

Problem is the same in deepword, dword and edward

**Comment by caracal7** [comment] 2019-08-21 08:31
If I rename edited file it can be edited again.

Maybe it is possible to disable localStorage and any caches?

**Comment by caracal7** [comment] 2019-08-21 08:38
I found hacky solution.
I can edit file again after logout. I think because it clear localStorage.

**Comment by coderaiser** [comment] 2019-08-21 11:32
@caracal7 could you please tell me what version do you use? The bug related to `localStorage` was fixed in [v13.2.0](https://github.com/coderaiser/cloudcmd/releases/tag/v13.2.0), and I can't reproduce this bug with the latest version.

**Comment by caracal7** [comment] 2019-08-21 11:42
I used 13.1.0 because it's installed by default
Moved to 13.2.0 and everything is working perfect
