### ISSUE TITLE
Support for unpacking rar archives

### ISSUE THREAD

**Issue by godfuture** [coderaiser/cloudcmd#222] opened 2019-01-26 14:34 UTC
Currently rar archives are not supported. It would help a lot, if rar could be unpacked.

* **Version** (`cloudcmd -v`): 
* **Node Version** `node -v`: 
* **OS** (`uname -a` on Linux): 
* **Browser name/version**: 
* **Used Command Line Parameters**: 
* **Changed Config**:

**Comment by coderaiser** [comment] 2019-01-26 14:44
This is a duplicate of #189. I agree rar suppor would help a lot, but there is only one [rar-stream](https://www.npmjs.com/package/rar-stream) implementations, and it is doesn't support decompression 🙂, so it is not very useful. If you will find any other implementation you can advice it.

Also you can write to author of [rar-stream](https://github.com/1313/rar-stream/issues/new) about decompression support 😉, it can speed things up.

**Closed by coderaiser** 2019-01-26 14:44 UTC
Labels: question

**Comment by godfuture** [comment] 2019-01-26 20:45
Well, I do not know anything of this rar-stream implementation. But its github page says: "Library for "unpacking" and reading files inside rar archives". Unpacking sounds like decompression, isn't it?

**Comment by coderaiser** [comment] 2019-01-27 11:18
Unfortunetly no. When you pack files, you move them in one big file, which has it’s on format, for example [tar](https://en.wikipedia.org/wiki/Tar_(computing) is a packer without compression and [gzip](https://en.wikipedia.org/wiki/Gzip) has compression but supports only one file.

This implementation can unpack but does not supports decompression, if I’ll embed it to Cloud Commander, first question you will ask: why can’t I decompress my archives 🙂. Looks like author see that his library needs nobody, that’s why he do not continue his work. If you don’t want to fork it, and implement decompression by yourself ask him about it.
