### ISSUE TITLE
Drag & drop of folder misses some files

### ISSUE THREAD

**Issue by wernight** [coderaiser/cloudcmd#78] opened 2016-10-22 22:33 UTC
* **Version** (`cloudcmd -v`): v5.7.0  (Docker container running on Linux)
* **Browser**: Chrome (latest stable)

Drag & drop of a folder from Windows to cloudcmd will miss the content of some files and not extract some other files. Try with a bunch of random binary files.

Drop & drop a folder from cloudcmd to Windows will generate a tar.gz that 7-zip says is invalid: Unexpected end of input.

Note: Tried on both the alpine and nodejs based versions.

**Comment by coderaiser** [comment] 2016-10-24 08:08
> Drag & drop of a folder from Windows to cloudcmd will miss the content of some files and not extract some other files. Try with a bunch of random binary files.

Unfortunately I can not try this on windows, but on Mac I can't reproduce. Could you please provide more details. Do you drop folders from Explorer or other applications?

> Drop & drop a folder from cloudcmd to Windows will generate a tar.gz that 7-zip says is invalid: Unexpected end of input.

Same with Mac, everything work as expected. Could you please, try to use

```
tar zxf folder_name.tar.gz
```

Does `tar` works better then `7zip` for you?

**Comment by coderaiser** [comment] 2016-10-24 09:39
> Drop & drop a folder from cloudcmd to Windows will generate a tar.gz that 7-zip says is invalid: Unexpected end of input.

Fixed in 7479ef7.

**Comment by wernight** [comment] 2016-10-24 12:51
Awesome! I'll try that.

**Comment by coderaiser** [comment] 2016-10-24 17:45
> Drag & drop of a folder from Windows to cloudcmd will miss the content of some files and not extract some other files. Try with a bunch of random binary files.

Can't reproduce on Win 10.

**Closed by coderaiser** 2016-10-24 17:45 UTC
Labels: bug
