### ISSUE TITLE
Can't edit files

### ISSUE THREAD

**Issue by kirtapix** [coderaiser/cloudcmd#207] opened 2018-11-30 11:06 UTC
* **Version** (`cloudcmd -v`): v11.8.2
* **Node Version** `node -v`: v8.11.1
* **OS** (`uname -a` on Linux): Linux NasPi 4.14.79+ #1159 Sun Nov 4 17:28:08 GMT 2018 armv6l GNU/
Linux                                                             
* **Browser name/version**: latest firefox
* **Used Command Line Parameters**: /
* **Changed Config**: /

Hi,

Since I upgraded cloudcmd, I can't edit files.
In firefox developer tool I can see that it can't load 2 scripts, when I hit "edit" button :
- modules/loadremote/lib/loadremote.js
- join/join.js
GET requests responses : 
- ENOENT: no such file or directory, lstat '/opt/nodejs/lib/node_modules/cloudcmd/modules/loadremote/lib/loadremote.js'
- ENOENT: no such file or directory, lstat '/opt/nodejs/lib/node_modules/cloudcmd/join/join.js'

When I browse to "/opt/nodejs/lib/node_modules/cloudcmd/" there is no "module" and "join" directories.

Thanks in advance for your response !

Edit :

Reverted back cloudcmd to 10.8.2 and I can edit again

**Comment by coderaiser** [comment] 2018-11-30 14:14
Hi @kirtapix, 

I can't reproduce this, looks like a problem with `service workers`.
Could you please go to URL `about:debugging#workers` and unregister all service workers? 

Is it helped?

**Comment by jcaron23** [comment] 2018-12-04 15:58
I have the same issue using cloudcmd as express middleware with a prefix (not sure if it's the same issue OP is facing or not, and not sure if the issue is in cloudcmd or the editors).

Even the example given in the [11.7.0 release notes](https://github.com/coderaiser/cloudcmd/releases/tag/v11.7.0) doesn't work. As soon as you try to edit a file, you get 404s for:
* `/cloudcmd/modules/loadremote/lib/loadremote.js`
* `/cloudcmd/join/join.js`

The "right" URLs should be:
* `/cloudcmd/edward/modules/loadremote/lib/loadremote.js`
* `/cloudcmd/edward/join/join.js`

(note the additional `/edward`).

I fixed those by adding redirects, and then you have additional issues with `/edit.json`, `/modules.json`, `/options.json`.

After that there are JS errors (`TypeError: undefined is not an object (evaluating 'module.local')` at `loadremote.js:66`), don't yet know where that comes from (removing the prefix in `app.use` everything works great, but I need the prefix).

The issue is probably related to https://github.com/coderaiser/cloudcmd/issues/200 or the related changes in the editors?

**Comment by coderaiser** [comment] 2018-12-04 18:42
I understood, there is such a bug with a `--prefix` option. Fixed with cbfce19f 🔨

**Comment by coderaiser** [comment] 2018-12-04 18:59
Landed in [v8.11.3](https://github.com/coderaiser/cloudcmd/releases/tag/v11.8.3) 🎉 .
It is works for you?

**Comment by jcaron23** [comment] 2018-12-04 22:33
@coderaiser Wow, that was quick! Definitely works much better now!

Just for completeness, I want to point out that there's an issue with the example in the 11.7.0 release notes, the socket doesn't work (as so configuration and console don't work either). My workaround is to use:

    const socket = io.listen(server, { path: '/cloudcmd/socket.io'});

instead of:

    const socket = io.listen(server);

But there may be another / a better way.

Thanks again for the very quick fix!

**Comment by coderaiser** [comment] 2018-12-05 09:20
@jcaron23 yes, you absolutely right, this is because when you set `prefix` it will affect `socketPath` as well, the same implementation used in [server/server.js](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/server/server.js#L54), thank you!

**Closed by coderaiser** 2018-12-05 09:20 UTC
Labels: browser, bug, firefox, linux, node, node v8, os, prefix

**Comment by kirtapix** [comment] 2018-12-27 22:49
Hi @coderaiser ,
Sorry for no response, was quite busy. It's working fine since your correction in 11.8.3.
Thanks a lot !
and thanks to @jcaron23 too, for completing my problem with his expert explanation
